<?php

/**
 * @file
 * Contains related_entities.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function related_entities_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the related_entities module.
    case 'help.page.related_entities':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module to display related entities based on entity view into block.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function related_entities_theme() {
  return [
    'related_entities' => [
      'variables' => ['entities' => NULL],
    ],
  ];
}
